### ISSUE TITLE
Publish version 1.1 to pub

### ISSUE THREAD

**Issue by Scorpiion** [exitlive/stripe-dart#20]
Hello,

Looking at the repo it looks like there is a version 1.1 of stripe-dart, but the last version on pub is 1.0.1. Is there a specific reason for this or have it simply just not been published yet? Is there a roadmap for the project?

**Comment by martflu** [comment]
I will try to find time next week to do a little housekeeping and put the latest version on pub. Bare in mind that this lib is only compatible to version stripe api version 2015-01-26 and not yet to 2015-03-24.

**Comment by Scorpiion** [comment]
Okay, thanks, good to know. Do you or @enyo use this lib for some live application at the moment?

**Comment by martflu** [comment]
Not yet, which is why there was little work done for this repository for some time now. But we are planning on using it in the near future. So sooner or later we will try to give this lib more attention.

**Comment by Scorpiion** [comment]
Check!

**Comment by enyo** [comment]
@Scorpiion we will make sure to update the library and keep it up to date. Since it is not yet in production in our software, the updates take a bit longer sometimes – but they're coming! (Thanks to @martflu )

**Comment by Scorpiion** [comment]
:+1:
